# Generated by Django 5.0.2 on 2024-02-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('criminality_index', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('travel_safety_report', models.TextField(null=True)),
                ('health_report', models.TextField(null=True)),
                ('vaccines', models.TextField(null=True)),
                ('diseases', models.TextField(null=True)),
            ],
        ),
    ]
